apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vyi3hr13i-nodejs
  janus-idp.io/tekton: vyi3hr13i-nodejs
  backstage.io/kubernetes-id: vyi3hr13i-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vyi3hr13i-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
